import sys
f = open("conda/audiorecorderConst.sh","w+")
f.write("osascript -e 'tell application \"Terminal\"\n")
f.write("\t\tset doneFile to \"")
f.write(sys.argv[1])
f.write("/done.data\"\n")
f.write("\t\tset writeHandler to open for access doneFile with write permission\n")
f.write("\t\ttry\n")
f.write("\t\t\tset eof of doneFile to 0 \n")
f.write("\t\t\twrite \"false\" to doneFile\n")
f.write("\t\t\tclose access writeHandler\n")
f.write("\t\ton error\n")
f.write("\t\t\tclose access writeHandler\n")
f.write("\t\tend try\n")
f.write("\t\tdo script \"\"\n")
f.write("\t\tset scriptWindow to front window\n")
f.write("\t\tdo script \"cd ")
f.write(sys.argv[1])
f.write("/conda\" in scriptWindow\n")
f.write("\t\tdo script \"./audioRecorderConstActivator.sh\" in scriptWindow\n")
f.write("\t\tset x to \"false\"\n")
f.write("\t\trepeat until x is equal to \"true\"\n")
f.write("\t\t\tset fileHandle to open for access doneFile\n")
f.write("\t\t\tset fileLines to paragraphs of (read fileHandle)\n")
f.write("\t\t\tclose access fileHandle\n")
f.write("\t\t\tset x to item 1 of fileLines\n")
f.write("\t\tend repeat\n")
f.write("\t\tclose scriptWindow\n")
f.write("end tell'")
f.close()

v = open("venv/audiorecorderConst.sh","w+")
v.write("osascript -e 'tell application \"Terminal\"\n")
v.write("\t\tset doneFile to \"")
v.write(sys.argv[1])
v.write("/done.data\"\n")
v.write("\t\tset writeHandler to open for access doneFile with write permission\n")
v.write("\t\ttry\n")
v.write("\t\t\tset eof of doneFile to 0 \n")
v.write("\t\t\twrite \"false\" to doneFile\n")
v.write("\t\t\tclose access writeHandler\n")
v.write("\t\ton error\n")
v.write("\t\t\tclose access writeHandler\n")
v.write("\t\tend try\n")
v.write("\t\tdo script \"\"\n")
v.write("\t\tset scriptWindow to front window\n")
v.write("\t\tdo script \"cd ")
v.write(sys.argv[1])
v.write("/venv\" in scriptWindow\n")
v.write("\t\tdo script \"./audioRecorderConstActivator.sh\" in scriptWindow\n")
v.write("\t\tset x to \"false\"\n")
v.write("\t\trepeat until x is equal to \"true\"\n")
v.write("\t\t\tset fileHandle to open for access doneFile\n")
v.write("\t\t\tset fileLines to paragraphs of (read fileHandle)\n")
v.write("\t\t\tclose access fileHandle\n")
v.write("\t\t\tset x to item 1 of fileLines\n")
v.write("\t\tend repeat\n")
v.write("\t\tclose scriptWindow\n")
v.write("end tell'")
v.close()
